In [1]:
import numpy as np
import os
from PIL import Image

In [2]:
train_clsnames = "/data/FSLDatasets/tieredImageNet/train_classnames.txt"
TRAIN_TIERED_IMAGE_DATASET_DIR = "/data/tiered_imagenet/train"
val_clsnames = "/data/FSLDatasets/tieredImageNet/val_classnames.txt"
VAL_TIERED_IMAGE_DATASET_DIR = "/data/tiered_imagenet/val"
test_clsnames = "/data/FSLDatasets/tieredImageNet/test_classnames.txt"
TEST_TIERED_IMAGE_DATASET_DIR = "/data/tiered_imagenet/test"

all_classnames = []

In [3]:
train_data = np.empty((448695,84,84,3), dtype='uint8') # 448695 is the total number of samples in training set.
train_label = np.empty(448695, dtype='uint16')
train_n = 0
with open(train_clsnames, "r") as f:
    for idx, line in enumerate(f):
        line = line.strip('\n')
        line = line.strip('\r')
        line = line.strip()
        print(idx, line)
        all_classnames.append(line)
        for file in os.listdir(os.path.join(TRAIN_TIERED_IMAGE_DATASET_DIR, line)):
            image = Image.open(os.path.join(TRAIN_TIERED_IMAGE_DATASET_DIR, line, file)).convert('RGB')
            img_ndarray = np.asarray(image.resize((84,84)), dtype='uint8')
            train_data[train_n] = img_ndarray
            train_label[train_n] = idx
            train_n += 1
assert(idx == 351-1 and train_n == 448695)
train_label[:5], train_label[1301], train_label[-5:], train_data[-1][-1][-1]

0 n01530575
1 n01531178
2 n01532829
3 n01534433
4 n01537544
5 n01558993
6 n01560419
7 n01580077
8 n01582220
9 n01592084
10 n01601694
11 n01675722
12 n01677366
13 n01682714
14 n01685808
15 n01687978
16 n01688243
17 n01689811
18 n01692333
19 n01693334
20 n01694178
21 n01695060
22 n01728572
23 n01728920
24 n01729322
25 n01729977
26 n01734418
27 n01735189
28 n01737021
29 n01739381
30 n01740131
31 n01742172
32 n01744401
33 n01748264
34 n01749939
35 n01751748
36 n01753488
37 n01755581
38 n01756291
39 n01847000
40 n01855032
41 n01855672
42 n01860187
43 n02002556
44 n02002724
45 n02006656
46 n02007558
47 n02009229
48 n02009912
49 n02011460
50 n02012849
51 n02013706
52 n02017213
53 n02018207
54 n02018795
55 n02025239
56 n02027492
57 n02028035
58 n02033041
59 n02037110
60 n02051845
61 n02056570
62 n02058221
63 n02088094
64 n02088238
65 n02088364
66 n02088466
67 n02088632
68 n02089078
69 n02089867
70 n02089973
71 n02090379
72 n02090622
73 n02090721
74 n02091032
75 n02091134
76 n02091244
77 n02091

(array([0, 0, 0, 0, 0], dtype=uint16),
 1,
 array([350, 350, 350, 350, 350], dtype=uint16),
 array([203, 207, 216], dtype=uint8))

In [4]:
val_data = np.empty((124261,84,84,3), dtype='uint8') # 124261 is the total number of samples in validation set.
val_label = np.empty(124261, dtype='uint16')
val_n = 0
with open(val_clsnames, "r") as f:
    for idx, line in enumerate(f):
        line = line.strip('\n')
        line = line.strip('\r')
        line = line.strip()
        print(line)
        all_classnames.append(line)
        for file in os.listdir(os.path.join(VAL_TIERED_IMAGE_DATASET_DIR, line)):
            image = Image.open(os.path.join(VAL_TIERED_IMAGE_DATASET_DIR, line, file)).convert('RGB')
            img_ndarray = np.asarray(image.resize((84,84)), dtype='uint8')
            val_data[val_n] = img_ndarray
            val_label[val_n] = idx + 351
            val_n += 1
assert(idx == 97-1 and val_n == 124261)
val_label[:5], val_label[1301], val_label[-5:], val_data[-1][-1][-1]

n02099267
n02099429
n02099601
n02099712
n02099849
n02100236
n02100583
n02100735
n02100877
n02101006
n02101388
n02101556
n02102040
n02102177
n02102318
n02102480
n02102973
n03207941
n03259280
n03297495
n03483316
n03584829
n03761084
n04070727
n04111531
n04442312
n04517823
n04542943
n04554684
n02791124
n02804414
n02870880
n03016953
n03018349
n03125729
n03131574
n03179701
n03201208
n03290653
n03337140
n03376595
n03388549
n03742115
n03891251
n03998194
n04099969
n04344873
n04380533
n04429376
n04447861
n04550184
n02666196
n02977058
n03180011
n03485407
n03496892
n03642806
n03832673
n04238763
n04243546
n04428191
n04525305
n06359193
n02966193
n02974003
n03425413
n03532672
n03874293
n03944341
n03992509
n04019541
n04040759
n04067472
n04371774
n04372370
n02701002
n02704792
n02814533
n02930766
n03100240
n03345487
n03417042
n03444034
n03445924
n03594945
n03670208
n03770679
n03777568
n03785016
n03796401
n03930630
n03977966
n04037443
n04252225
n04285008
n04461696
n04467665


(array([351, 351, 351, 351, 351], dtype=uint16),
 352,
 array([447, 447, 447, 447, 447], dtype=uint16),
 array([46, 63, 91], dtype=uint8))

In [5]:
test_data = np.empty((206209,84,84,3), dtype='uint8') # 206209 is the total number of samples in testing set.
test_label = np.empty(206209, dtype='uint16')
test_n = 0
with open(test_clsnames, "r") as f:
    for idx, line in enumerate(f):
        line = line.strip('\n')
        line = line.strip('\r')
        line = line.strip()
        print(line)
        all_classnames.append(line)
        for file in os.listdir(os.path.join(TEST_TIERED_IMAGE_DATASET_DIR, line)):
            image = Image.open(os.path.join(TEST_TIERED_IMAGE_DATASET_DIR, line, file)).convert('RGB')
            img_ndarray = np.asarray(image.resize((84,84)), dtype='uint8')
            test_data[test_n] = img_ndarray
            test_label[test_n] = idx + 351 + 97
            test_n += 1
assert(idx == 160-1 and test_n == 206209)
test_label[:5], test_label[1301], test_label[-5:], test_data[-1][-1][-1]

n03314780
n07565083
n07579787
n07583066
n07584110
n07590611
n07613480
n07614500
n07615774
n07697313
n07697537
n07802026
n07831146
n07836838
n07860988
n07873807
n07875152
n07880968
n07892512
n07920052
n07930864
n07932039
n01440764
n01443537
n01484850
n01491361
n01494475
n01496331
n01498041
n02514041
n02526121
n02536864
n02606052
n02607072
n02640242
n02641379
n02643566
n02655020
n02104029
n02104365
n02105056
n02105162
n02105251
n02105412
n02105505
n02105641
n02105855
n02106030
n02106166
n02106382
n02106550
n02106662
n02107142
n02107312
n02107574
n02107683
n02107908
n02108000
n02108089
n02108422
n02108551
n02108915
n02109047
n02109525
n02109961
n02110063
n02110185
n02110627
n02165105
n02165456
n02167151
n02168699
n02169497
n02172182
n02174001
n02177972
n02190166
n02206856
n02219486
n02226429
n02229544
n02231487
n02233338
n02236044
n02256656
n02259212
n02264363
n02268443
n02268853
n02276258
n02277742
n02279972
n02280649
n02281406
n02281787
n02788148
n02894605
n03000134
n03160309
n03459775


(array([448, 448, 448, 448, 448], dtype=uint16),
 449,
 array([607, 607, 607, 607, 607], dtype=uint16),
 array([56, 87, 79], dtype=uint8))

In [7]:
all_classnames = np.array(all_classnames)
print(all_classnames.shape)

(608,)


In [8]:
_TIEREDIMAGENET_DATASET_DIR = '/data/FSLDatasets/tieredImageNet'
np.save(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'train_data.npy'), train_data)
np.save(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'train_label.npy'), train_label)
np.save(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'val_data.npy'), val_data)
np.save(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'val_label.npy'), val_label)
np.save(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'test_data.npy'), test_data)
np.save(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'test_label.npy'), test_label)

In [9]:
print(np.load(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'train_data.npy')).shape)
print(np.load(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'train_label.npy')).shape)
print(np.load(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'val_data.npy')).shape)
print(np.load(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'val_label.npy')).shape)
print(np.load(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'test_data.npy')).shape)
print(np.load(os.path.join(_TIEREDIMAGENET_DATASET_DIR, 'test_label.npy')).shape)

(448695, 84, 84, 3)
(448695,)
(124261, 84, 84, 3)
(124261,)
(206209, 84, 84, 3)
(206209,)
